services:
  backend:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    volumes:
      - ../.:${WORK_DIR}
    ports:
      - "5000:5000"
    working_dir: ${WORK_DIR}
    command: "/bin/bash docker/setup.sh"